session_name: dev
windows:
  - window_name: ros2_vtr
    layout: tiled
    panes:
      - shell_command:
          - cd $VTRROOT/rosbags/torrent_rosbags
          - ros2 bag play tf -l
      - shell_command:
          - cd $VTRROOT/rosbags/torrent_rosbags
          - source $VTRSRC/main/install/setup.bash
          - ros2 bag play dome_loop/ -r 0.25
      - shell_command:
          - cd $VTRROOT/torrent_ws/scripts
          - rm -rf $VTRTEMP/pgs/rutias
          - source $VTRSRC/main/install/setup.bash
          - python3 posegraph/live_reconstruct_posegraph.py -b utias